# Generated by Django 5.0 on 2023-12-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Company',
        ),
    ]
