# Generated by Django 5.0 on 2023-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='Phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
