# Generated by Django 5.0 on 2023-12-15 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_usersettings_usersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='comment',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='company_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='dni',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='firstName',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='lastName',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='rol_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.rol'),
        ),
    ]
