# Generated by Django 5.0 on 2023-12-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rol_remove_usersetting_comment_usersetting_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='company_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='rol_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='base.rol'),
        ),
    ]
