# Generated by Django 5.0 on 2023-12-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0009_alter_usersetting_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='rol_id',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='group_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
