# Generated by Django 5.0 on 2023-12-15 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0010_remove_usersetting_rol_id_usersetting_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GroupModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('module_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='base.module')),
            ],
        ),
    ]
