# Generated by Django 5.0 on 2023-12-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_usersetting_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='active',
        ),
    ]
