# Generated by Django 5.0 on 2023-12-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_usersetting_active'),
    ]

    operations = [
    ]
