# Generated by Django 5.0 on 2023-12-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_usersetting_company_id_and_more'),
    ]

    operations = [
    ]
