# Generated by Django 5.0 on 2023-12-27 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_clientdata_country_clientdata_state'),
    ]

    operations = [
    ]
