# Generated by Django 5.0 on 2023-12-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_usersetting_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='groupmodule',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='groupmodule',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='GroupModule',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
